### ISSUE TITLE
cucumber-rest-assured-extent-report-plugin readme doc - tutorial article(Link) is not working

### ISSUE THREAD

**Issue by kishore24k** [grasshopper7/cucumber-rest-assured-extent-report-plugin#2]
[cucumber-rest-assured-extent-report-plugin](https://github.com/grasshopper7/cucumber-rest-assured-extent-report-plugin)

=> readme.md
                        Default configuration details and tips be modify them can be found in the article (https://ghchirp.online/4199/)

https://ghchirp.online/4199/ - Not working

Issue: The link is not working...

**Comment by grasshopper7** [comment]
https://ghchirp.site/4199/

Will update this.

**Comment by AlexBravo95** [comment]
Hi, update documentation ?
